### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by turbosheep44** [jmp/poker-hand-evaluator#1]
# Problem

From the README file for this repository:

> The `evaluate` method returns the value of a hand as an integer between 1 and 7462. The higher the value, the more valuable the hand.

However, from the test file the best hands have the lowest values:

> Ts Js Qs Ks As 1
> 9s Ts Js Qs Ks 2
> 8s 9s Ts Js Qs 3

and the worst hands have the highest values:

> 2c 3c 4c 5c 7d 7462
> 2c 3c 4c 6c 7d 7461
> 2c 3c 5c 6c 7d 7460

# Expected Fix

Update the documentation to properly reflect that lower values represent better hands.

**Comment by jmp** [comment]
Thanks, fixed in fefc743fa97c7ec1bd28a00c14b0fd255f62af84.
